add_library(moke INTERFACE)
target_include_directories(moke INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/include)

if (MOKE_PLATFORM STREQUAL cuda)
target_compile_definitions(moke INTERFACE -DMOKE_PLATFORM_CUDA)
target_link_libraries(moke INTERFACE CUDA::cudart)
elseif (MOKE_PLATFORM STREQUAL hip)
target_compile_definitions(moke INTERFACE -DMOKE_PLATFORM_HIP)
target_link_libraries(moke INTERFACE hip::host)
endif()
