enable_language(CUDA)
find_package(CUDAToolkit REQUIRED)

set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_EXTENSIONS ON)

message(${CMAKE_CUDA_COMPILER})

if (CMAKE_CUDA_COMPILER MATCHES "clang")
    set(CMAKE_CUDA_SEPARABLE_COMPILATION OFF)
else()
    set(CMAKE_CUDA_SEPARABLE_COMPILATION ON)
endif()